/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import MetroMendeley.Author;
import MetroMendeley.HashTable;
import MetroMendeley.LinkedList;
import MetroMendeley.ReadFile;
import MetroMendeley.Summary;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author Rolando
 */
public class MainUI extends javax.swing.JFrame {
    
    public static LinkedList<Summary> summarysList = new LinkedList();
    public static LinkedList<Author> authorsList = new LinkedList();
    public static LinkedList<String> keywordList = new LinkedList();
    public static HashTable<String, Summary> hashTable = new HashTable();
    public static HashTable<String, Summary> hashTableKeywords = new HashTable();
    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
        //Lectura del archivo de texto de la base de datos
        ReadFile nfile = new ReadFile();
        
        try {
            String path = "test\\summarys.txt";
            String txt = nfile.readTxt(path);
            File file = new File(path);
            if (!txt.isBlank()) {
                String[] txtFinal = txt.split("¬");
                
                for (int i = 0; i < txtFinal.length - 1; i++) {
                    Summary summary = nfile.readSummary(txtFinal[i]);
                    
                    if (summary != null) {
                        hashTable.add(summary);
                        hashTableKeywords.add2(summary);

                    }
                             
                }
      
            } else {
                JOptionPane.showMessageDialog(null, "La base de datos se encuentra vacía. Cargue un archivo para agregar información!"); 
            }
            
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error al leer el archivo: " + e);
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Amazon = new javax.swing.JLabel();
        searchSummary = new javax.swing.JButton();
        analyzeSummary = new javax.swing.JButton();
        addSummary = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Amazon.setFont(new java.awt.Font("Microsoft YaHei", 1, 36)); // NOI18N
        Amazon.setForeground(new java.awt.Color(255, 255, 153));
        Amazon.setText("METRO MENDELEY");
        jPanel1.add(Amazon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 370, 60));

        searchSummary.setBackground(new java.awt.Color(255, 255, 153));
        searchSummary.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        searchSummary.setForeground(new java.awt.Color(51, 51, 51));
        searchSummary.setText("Buscar Investigaciones");
        searchSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchSummaryActionPerformed(evt);
            }
        });
        jPanel1.add(searchSummary, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 190, 40));

        analyzeSummary.setBackground(new java.awt.Color(255, 255, 153));
        analyzeSummary.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        analyzeSummary.setForeground(new java.awt.Color(51, 51, 51));
        analyzeSummary.setText("Analizar Resumen");
        analyzeSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyzeSummaryActionPerformed(evt);
            }
        });
        jPanel1.add(analyzeSummary, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 190, 40));

        addSummary.setBackground(new java.awt.Color(255, 255, 153));
        addSummary.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        addSummary.setForeground(new java.awt.Color(51, 51, 51));
        addSummary.setText("Agregar Resumen");
        addSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSummaryActionPerformed(evt);
            }
        });
        jPanel1.add(addSummary, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 190, 40));

        exit.setBackground(new java.awt.Color(255, 51, 51));
        exit.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        exit.setForeground(new java.awt.Color(51, 51, 51));
        exit.setText("Salir del programa");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 150, 40));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 153));
        jLabel1.setText("(Guarda la información actual)");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 210, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchSummaryActionPerformed
        SearchSummaryUI searchSummary = new SearchSummaryUI(this);
    }//GEN-LAST:event_searchSummaryActionPerformed

    private void analyzeSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyzeSummaryActionPerformed
        AnalyzeSummaryUI analyzeSummary = new AnalyzeSummaryUI(this);
    }//GEN-LAST:event_analyzeSummaryActionPerformed

    private void addSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSummaryActionPerformed
        AddSummaryUI addSummary = new AddSummaryUI(this);

    }//GEN-LAST:event_addSummaryActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        try {
        
            JOptionPane.showMessageDialog(null, "Se ha guardado toda la información correctamente! Hasta luego!");
            System.exit(0);

        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Se ha producido un error: " + e);
        }

    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Amazon;
    private javax.swing.JButton addSummary;
    private javax.swing.JButton analyzeSummary;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton searchSummary;
    // End of variables declaration//GEN-END:variables
}
