/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface;

import MetroMendeley.LinkedList;
import MetroMendeley.Summary;
import static UserInterface.MainUI.hashTable;
import static UserInterface.MainUI.hashTableKeywords;
import static UserInterface.MainUI.summarysList;
import javax.swing.JOptionPane;

/**
 *
 * @author Rolando
 */
public class SelectKeywordSummaryUI extends javax.swing.JFrame {
   
    
    public static SearchKeywordsUI v1;
    public static String keywordStatic;
    /**
     * Creates new form JFileChooser
     * @param v1 (Ventana principal)
     */
    public SelectKeywordSummaryUI(SearchKeywordsUI v1, String keywordStatic) {
        initComponents();
        this.v1 = v1;
        this.keywordStatic = keywordStatic;
 
        v1.setVisible(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        try {
            System.out.println(hashTableKeywords.getSize());
            LinkedList<Summary> summarysKeyword = hashTableKeywords.filterByKeyword(keywordStatic);
            
            System.out.println("llego");
            String s = summarysKeyword.printList();
            System.out.println(s);
            String[] shownSummarys = new String[summarysKeyword.getSize()];
            for (int i = 0; i < shownSummarys.length; i++) {
                shownSummarys[i] = summarysKeyword.getElement(i).getTitle();
            }
        
        summarysShown.setListData(shownSummarys);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Second error" + e);
        }
        
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        keywordName = new javax.swing.JLabel();
        choose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        summarysShown = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setBackground(new java.awt.Color(204, 255, 255));
        back.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        back.setForeground(new java.awt.Color(51, 51, 51));
        back.setText("Volver");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 80, 30));

        keywordName.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        keywordName.setForeground(new java.awt.Color(255, 255, 153));
        keywordName.setText("RESÚMENES CON LA PALABRA CLAVE INGRESADA ");
        jPanel1.add(keywordName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 650, 50));

        choose.setBackground(new java.awt.Color(255, 255, 153));
        choose.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        choose.setForeground(new java.awt.Color(51, 51, 51));
        choose.setText("Mostrar detalles");
        choose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseActionPerformed(evt);
            }
        });
        jPanel1.add(choose, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 140, 40));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 153));
        jLabel2.setText("Seleccione un resumen y luego presione el botón \"Mostrar detalles\"");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 440, 30));

        summarysShown.setBackground(new java.awt.Color(102, 102, 102));
        summarysShown.setForeground(new java.awt.Color(255, 255, 255));
        summarysShown.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(summarysShown);

        jScrollPane2.setViewportView(jScrollPane1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 450, 150));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.setVisible(false);
        v1.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void chooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseActionPerformed
       try {
           String selected = summarysShown.getSelectedValue();
           
           Summary summary = hashTable.get(selected);
           
           ShowDetailsUI showDetailsUI = new ShowDetailsUI(this, summary);
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Debe escoger uno de los resúmenes");
        }
        
    }//GEN-LAST:event_chooseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectKeywordSummaryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectKeywordSummaryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectKeywordSummaryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectKeywordSummaryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectKeywordSummaryUI(v1, keywordStatic).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton choose;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel keywordName;
    private javax.swing.JList<String> summarysShown;
    // End of variables declaration//GEN-END:variables
}
